from tkinter import *
window=Tk()
window.geometry("650x650")

Label(window,text="Car rental receipt",font=2).grid(row=0,column=1,columnspan=2)
Label(window,text="").grid(row=0,column=0)
Label(window,text="Date").grid(row=1,column=0)
Label(window,text="Receipt").grid(row=2,column=0)
Label(window,text="Rental company info").grid(row=3,column=0)
Label(window,text="Lessee info").grid(row=3,column=2)
Label(window,text="Company").grid(row=4,column=0)
Label(window,text="Name").grid(row=4,column=2)
Label(window,text="Representative").grid(row=5,column=0)
Label(window,text="Licence").grid(row=5,column=2)
Label(window,text="Location").grid(row=6,column=0)
Label(window,text="Address").grid(row=6,column=2)
Label(window,text="City/state/Zip").grid(row=7,column=0)
Label(window,text="City/state/Zip").grid(row=7,column=2)
Label(window,text="Phone").grid(row=8,column=0)
Label(window,text="Phone").grid(row=8,column=2)
Label(window,text="",font=2).grid(row=9,column=1,columnspan=2)
Label(window,text="Vehicle information",font=2).grid(row=10,column=1,columnspan=2)
Label(window,text="VIN").grid(row=11,column=0)
Label(window,text="Registration#").grid(row=11,column=2)
Label(window,text="Make").grid(row=12,column=0)
Label(window,text="Model").grid(row=12,column=2)
Label(window,text="Year").grid(row=13,column=0)
Label(window,text="Mileage").grid(row=13,column=2)
Label(window,text="color").grid(row=14,column=0)
Label(window,text="").grid(row=15,column=0)


#Entries
Entry(window).grid(row=1,column=1)
Entry(window).grid(row=2,column=1)
Entry(window).grid(row=4,column=1)
Entry(window).grid(row=4,column=3)
Entry(window).grid(row=5,column=1)
Entry(window).grid(row=5,column=3)
Entry(window).grid(row=6,column=1)
Entry(window).grid(row=6,column=3)
Entry(window).grid(row=7,column=1)
Entry(window).grid(row=7,column=3)
Entry(window).grid(row=8,column=1)
Entry(window).grid(row=11,column=1)
Entry(window).grid(row=11,column=3)
Entry(window).grid(row=12,column=1)
Entry(window).grid(row=12,column=3)
Entry(window).grid(row=13,column=1)
Entry(window).grid(row=13,column=3)
Entry(window).grid(row=14,column=1)

l_e=Entry(window,width=200,state='disabled',cursor='arrow')
l_e.place(x=5,y=350,height=200)

Label(l_e,text="Vin").grid(row=0,column=0)
Label(l_e,text="Cost/day").grid(row=0,column=1)
Label(l_e,text="# of days").grid(row=0,column=2)
Label(l_e,text="Additional cost").grid(row=0,column=3)
Label(l_e,text="Line total").grid(row=0,column=4)
Label(l_e,text="Payment method").grid(row=4,column=0)

Entry(l_e).grid(row=1,column=0)
Entry(l_e).grid(row=1,column=1)
Entry(l_e).grid(row=1,column=2)
Entry(l_e).grid(row=1,column=3)
Entry(l_e).grid(row=1,column=4)
Entry(l_e).grid(row=2,column=0)
Entry(l_e).grid(row=2,column=1)
Entry(l_e).grid(row=2,column=2)
Entry(l_e).grid(row=2,column=3)
Entry(l_e).grid(row=2,column=4)
Entry(l_e).grid(row=3,column=0)
Entry(l_e).grid(row=3,column=1)
Entry(l_e).grid(row=3,column=2)
Entry(l_e).grid(row=3,column=3)
Entry(l_e).grid(row=3,column=4)
Entry(l_e).grid(row=5,column=2)
Entry(l_e).grid(row=6,column=1)
Entry(l_e).grid(row=7,column=1)

e1=Entry(l_e)
e1.grid(row=5,column=3)
e1.insert(INSERT,"Subtotal")
e2=Entry(l_e)
e2.grid(row=5,column=4)
e3=Entry(l_e)
e3.grid(row=6,column=3)
e3.insert(INSERT,"Tax")
e4=Entry(l_e).grid(row=6,column=4)
e5=Entry(l_e)
e5.grid(row=7,column=3)
e5.insert(INSERT,"Total:")
e6=Entry(l_e).grid(row=7,column=4)
e7=Entry(l_e)
e7.grid(row=8,column=3)
e7.insert(INSERT,"Amount paid")
e8=Entry(l_e).grid(row=8,column=4)

Checkbutton(l_e,text="Cash").grid(row=5,column=0)
Checkbutton(l_e,text="Check no").grid(row=5,column=1)
Checkbutton(l_e,text="Credit no.").grid(row=6,column=0)
Checkbutton(l_e,text="Other").grid(row=7,column=0)

window.mainloop()